version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates that might cause breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "ci-cd"
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "ci"
      include: "scope"