version: '3.8'

services:
  scroll-keeper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scroll-keeper
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - scroll-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - scroll-network

  # Optional vector database for production deployments
  # Uncomment to enable
  # vector-db:
  #   image: qdrant/qdrant
  #   container_name: vector-db
  #   restart: unless-stopped
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - vector-data:/qdrant/storage
  #   networks:
  #     - scroll-network

networks:
  scroll-network:
    driver: bridge

volumes:
  scroll-data:
  # vector-data: