name: Auto-Sync from Replit

on:
  workflow_dispatch:
    # This allows manual triggering via the GitHub UI
    # or via the API from the Replit script

jobs:
  sync-from-replit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Add Replit remote
        run: |
          # Use the secret containing your Replit Git URL
          git remote add replit ${{ secrets.REPLIT_GIT_URL }}
      
      - name: Fetch from Replit
        run: |
          git fetch replit
      
      - name: Attempt merge
        run: |
          # Try to merge automatically
          if git merge replit/main -m "Auto-sync from Replit"; then
            echo "Automatic merge successful"
          else
            # If there are conflicts, abort the merge
            git merge --abort
            
            # Create a new branch with the Replit changes
            git checkout -b replit-sync-$(date +%Y%m%d%H%M%S) replit/main
            
            # Push the new branch
            git push origin replit-sync-$(date +%Y%m%d%H%M%S)
            
            echo "Merge conflicts detected. Created a new branch with Replit changes."
            exit 1
          fi
      
      - name: Push changes
        run: |
          git push origin main