name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to IPFS via Storacha
        run: node --experimental-modules scripts/deploy-to-storacha.js
        env:
          STORACHA_API_KEY: ${{ secrets.STORACHA_API_KEY }}
          ENS_PRIVATE_KEY: ${{ secrets.ENS_PRIVATE_KEY }}
          ENS_DOMAIN: ${{ secrets.ENS_DOMAIN }}

      - name: Log deployment info
        run: |
          echo "🚀 Deployment complete!"
          echo "Check the job logs above for IPFS URLs and ENS domain info."